version: "3"
services:
  web:
    build: .
    ports:
        - "5000:5000"
    volumes:
        - ".:/app"
  redis:
    image: "redis:alpine"
    ports: 
        - "6379:6379"
  mongo-db:
    image: mongo
    ports:
        - "27017:27017"
    container_name: mongo-db
    volumes:
        - ./db/:/data/db
  mongo-express:
    image: mongo-express
    ports:
        - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo-db:27017
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"